# Generated by Django 2.2.28 on 2023-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
    ]
